services:
  ghibli_db_prd:
    image: postgres:15-alpine
    container_name: ghibli_db_prd
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    security_opt:
      - no-new-privileges:true
    volumes:
      - postgres_data_prd:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend_prd

  ghibli_api_prd:
    build:
      context: ./
      dockerfile: containers/api/Dockerfile.prd
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - "8881"
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      ghibli_db_prd:
        condition: service_healthy
    env_file:      
      - .env.prd
    environment:
      - ENVIRONMENT=production
      - CREATE_INITIAL_DATA=false
      - WORKERS_PER_CORE=1
      - MAX_WORKERS=2
      - WEB_CONCURRENCY=2
    networks:
      - backend_prd

  ghibli_redis_prd:
    image: redis:alpine
    container_name: ghibli_redis_prd
    command: redis-server --appendonly yes
    volumes:
      - redis_data_prd:/data
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
    security_opt:
      - no-new-privileges:true
    restart: always
    networks:
      - backend_prd
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  nginx_prd:
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile
    container_name: nginx_prd
    ports:
      - "8080:80" 
    depends_on:
      - ghibli_api_prd
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M
    security_opt:
      - no-new-privileges:true
    restart: always
    networks:
      - backend_prd

volumes:
  postgres_data_prd:
  redis_data_prd:

networks:
  backend_prd:
    driver: bridge
    name: ghibli_network_prd